import Head from "next/head";
import Navbar from "../components/Navbar";
import { Box, Container, Text } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text color="white">Hello</Text>
    </>
  );
}
