import Head from "next/head";
import { Box, Flex, HStack, SimpleGrid, Spacer } from "@chakra-ui/react";
import algoliasearch from "algoliasearch/lite";
import { InstantSearch, Stats } from "react-instantsearch";
import CustomHits from "../components/CustomHits";
import CustomSortBy from "../components/CustomSortBy";
import Sidebar from "../components/Sidebar";

const searchClient = algoliasearch(
  process.env.NEXT_PUBLIC_ALGOLIA_APP_ID,
  process.env.NEXT_PUBLIC_ALGOLIA_SEARCH_KEY
);

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InstantSearch searchClient={searchClient} indexName="floorPlans">
        <Flex h="full">
          <Box bgColor="#1e1e1e" minWidth="30%" height="100%" p="5">
            <Sidebar />
          </Box>
          <Box
            w="100%"
            h="100%"
            maxHeight="calc(100vh - 4rem)"
            overflowY="scroll"
            overflowX="hidden"
            p={5}
          >
            <HStack mb="5" overflow="auto" color="white">
              <Stats
                translations={{
                  stats(nbHits) {
                    return `${nbHits} results found`;
                  },
                }}
              />

              <Spacer />
              <CustomSortBy
                items={[
                  { label: "Default", value: "floorPlans" },
                  { label: "Bedrooms (asc)", value: "floorPlans_bedrooms_asc" },
                  {
                    label: "Bedrooms (desc)",
                    value: "floorPlans_bedrooms_desc",
                  },
                  { label: "Plan Width (asc)", value: "floorPlans_width_asc" },
                  {
                    label: "Plan Width (desc)",
                    value: "floorPlans_width_desc",
                  },
                  { label: "Plan Depth (asc)", value: "floorPlans_depth_asc" },
                  {
                    label: "Plan Depth (desc)",
                    value: "floorPlans_depth_desc",
                  },
                ]}
              />
            </HStack>
            <SimpleGrid columns={[1, 1, 1, 2]} spacing={5}>
              <CustomHits />
            </SimpleGrid>
          </Box>
        </Flex>
      </InstantSearch>
    </>
  );
}
